// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateBookInput struct {
	Title     string  `json:"title"`
	Author    string  `json:"author"`
	Publisher *string `json:"publisher,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBookInput struct {
	Title     *string `json:"title,omitempty"`
	Author    *string `json:"author,omitempty"`
	Publisher *string `json:"publisher,omitempty"`
}
